services:
    nginx:
        container_name: nginx_data_api
        image: mirror.gcr.io/nginx:1.28-alpine
        restart: always
        ports:
            - "8100:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/app
        depends_on:
            - app

    app:
        container_name: app_data_api
        build:
            context: .
            dockerfile: .docker/app/DockerfileLocal
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1001}
        command: [ 'php-fpm', '--nodaemonize' ]
        depends_on:
            - postgres
        working_dir: /var/www/app
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./:/var/www/app
        environment:
            UID: ${UID:-1000}
            GID: ${GID:-1001}
            CORS_ALLOW_ORIGIN: '*'

    postgres:
        container_name: postgres_data_api
        image: mirror.gcr.io/postgres:${POSTGRES_VERSION:-16}-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        ports:
            - "5432"

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - "8110:8080"
        depends_on:
            - postgres

volumes:
    postgres_data:
